version: "3.9"
services:
  sales_mysql:
    image: mysql/mysql-server:8.0
    container_name: sales_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - 'sales-backend-mysql:/var/lib/mysql'
    networks:
      - sales-backend
  sales_backend:
    container_name: sales_backend
    depends_on:
      - sales_mysql
    build:
      dockerfile: Dockerfile
    environment:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
    ports:
      - "8085:8085"
    networks:
      - sales-backend

networks:
  sales-backend:
    driver: bridge

volumes:
  sales-backend-mysql:
    driver: local